### ISSUE TITLE
[FEATURE] Shorter implementation `OutputType` enum using `magic_enum` library.

### ISSUE THREAD

**Issue by lokitkhemka** [TLCFEM/suanPan#230]
**Feature**
It is strictly not a feature, but more a suggestion for code improvement.

I was reading through the code and I found that the implementation of `OutputType` enum was too long, there were about 162 members in the enum class and I thought to myself there should be an easier way to write this. I stumbled upon the `magic_enum`, a header-only library, which simplifies it to a great extent. The implementation of `to_name` and `to_token` functions are as follows:

```
#define MAGIC_ENUM_RANGE_MIN 0
#define MAGIC_ENUM_RANGE_MAX 256
#include <magic_enum/magic_enum.hpp>

    

std::string to_name(const OutputType L)
{
    OutputType type = L;
    std::string out(magic_enum::enum_name(type));
    return out;
}

OutputType to_token(const char* c)
{
    std::string in(c);
    auto type = magic_enum::enum_cast<OutputType>(in);
    if (type.has_value())
    {
        return type.value();
    }
    return OutputType::NL;
}
```

**References**
[Relevant Stackoverflow Question](https://stackoverflow.com/questions/28828957/how-to-convert-an-enum-to-a-string-in-modern-c/55312360#55312360)
[Link to `magic_enum` library](https://github.com/Neargye/magic_enum)

**Comment by TLCFEM** [comment]
Yeah indeed, I did not have a better solution at the time.

I've starred [magic_enum](https://github.com/Neargye/magic_enum), seems to be very neat.

Please let me know if you are interested in a PR or something similar, since you've presented a solution here.

Otherwise I'll find time to implement it.
